name: build
on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: unzip -q ArmorSense-1.0.9-mc26.1-source-v2.zip -d armorsense-build
      - uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - working-directory: armorsense-build/ArmorSense-1.0.9-mc26.1
        run: chmod +x ./gradlew && ./gradlew build --stacktrace
      - if: always()
        uses: actions/upload-artifact@v7
        with:
          name: ArmorSense-1.0.9-mc26.1
          path: armorsense-build/ArmorSense-1.0.9-mc26.1/build/libs/
