name: build
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: unzip -q DonutBalanceDisplay-1.0.2-source.zip -d donut-build
      - uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - working-directory: donut-build/DonutBalanceDisplay
        run: chmod +x ./gradlew && ./gradlew build --stacktrace
      - if: always()
        uses: actions/upload-artifact@v7
        with:
          name: DonutBalanceDisplay-1.0.2-mc26.2
          path: donut-build/DonutBalanceDisplay/build/libs/
