name: build
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: unpack Capybara source
        run: unzip -q capybara-source-v2.zip -d capybara-build
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: build
        working-directory: capybara-build
        run: chmod +x ./gradlew && ./gradlew build --stacktrace
      - name: capture build artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: Capybara-build
          path: capybara-build/build/libs/
